function imagesource (x) {
	switch(x)
	{
		case 1:document.getElementById('portfolio-show-img').src="img/portfolio/1.jpg";
				break;
		case 2:document.getElementById('portfolio-show-img').src="img/portfolio/2.jpg";
				break;
		case 3:document.getElementById('portfolio-show-img').src="img/portfolio/3.jpg";
				break;
		case 4:document.getElementById('portfolio-show-img').src="img/portfolio/4.jpg";
				break;
		case 5:document.getElementById('portfolio-show-img').src="img/portfolio/5.jpg";
				break;
		case 6:document.getElementById('portfolio-show-img').src="img/portfolio/6.jpg";
				break;
		case 7:document.getElementById('portfolio-show-img').src="img/portfolio/7.jpg";
				break;
		case 8:document.getElementById('portfolio-show-img').src="img/portfolio/8.jpg";
				break;
		case 9:document.getElementById('portfolio-show-img').src="img/portfolio/9.jpg";
				break;
		case 10:document.getElementById('portfolio-show-img').src="img/portfolio/10.jpg";
				break;
		case 11:document.getElementById('portfolio-show-img').src="img/portfolio/11.jpg";
				break;
		case 12:document.getElementById('portfolio-show-img').src="img/portfolio/12.jpg";
				break;
		case 13:document.getElementById('portfolio-show-img').src="img/portfolio/13.jpg";
				break;
		case 14:document.getElementById('portfolio-show-img').src="img/portfolio/14.jpg";
				break;	
		case 15:document.getElementById('portfolio-show-img').src="img/portfolio/15.jpg";
				break;
		case 16:document.getElementById('portfolio-show-img').src="img/portfolio/16.jpg";
				break;
		case 17:document.getElementById('portfolio-show-img').src="img/portfolio/17.jpg";
				break;
		case 18:document.getElementById('portfolio-show-img').src="img/portfolio/18.jpg";
				break;
		case 19:document.getElementById('portfolio-show-img').src="img/portfolio/19.jpg";
				break;
		case 20:document.getElementById('portfolio-show-img').src="img/portfolio/20.jpg";
				break;
		case 21:document.getElementById('portfolio-show-img').src="img/portfolio/21.jpg";
				break;
		case 22:document.getElementById('portfolio-show-img').src="img/portfolio/22.jpg";
				break;
		case 23:document.getElementById('portfolio-show-img').src="img/portfolio/23.jpg";
				break;
		case 24:document.getElementById('portfolio-show-img').src="img/portfolio/24.jpg";
				break;
		case 25:document.getElementById('portfolio-show-img').src="img/portfolio/25.jpg";
				break;
		case 26:document.getElementById('portfolio-show-img').src="img/portfolio/26.jpg";
				break;
		case 27:document.getElementById('portfolio-show-img').src="img/portfolio/27.jpg";
				break;
		case 28:document.getElementById('portfolio-show-img').src="img/portfolio/28.jpg";
				break;
		case 29:document.getElementById('portfolio-show-img').src="img/portfolio/29.jpg";
				break;
		case 30:document.getElementById('portfolio-show-img').src="img/portfolio/30.jpg";
				break;
		case 31:document.getElementById('portfolio-show-img').src="img/portfolio/31.jpg";
				break;
		case 32:document.getElementById('portfolio-show-img').src="img/portfolio/32.jpg";
				break;
		case 33:document.getElementById('portfolio-show-img').src="img/portfolio/33.jpg";
				break;
		case 34:document.getElementById('portfolio-show-img').src="img/portfolio/34.jpg";
				break;
		case 35:document.getElementById('portfolio-show-img').src="img/portfolio/35.jpg";
				break;
		case 36:document.getElementById('portfolio-show-img').src="img/portfolio/36.jpg";
				break;
		case 37:document.getElementById('portfolio-show-img').src="img/portfolio/37.jpg";
				break;
		case 38:document.getElementById('portfolio-show-img').src="img/portfolio/38.jpg";
				break;
		case 39:document.getElementById('portfolio-show-img').src="img/portfolio/39.jpg";
				break;
		case 40:document.getElementById('portfolio-show-img').src="img/portfolio/40.jpg";
				break;
		case 41:document.getElementById('portfolio-show-img').src="img/portfolio/41.jpg";
				break;
		case 42:document.getElementById('portfolio-show-img').src="img/portfolio/42.jpg";
				break;		
	}
}